version: '3.8'
services:
  llama:
    build: .
    container_name: llama-api
    ports:
      - "8000:8000"
    volumes:
      - "C:/Users/username/weights/llama/text:/app/llama/weights"
    environment:
      - MODEL=/app/llama/weights
    command: python3 /app/app.py
