# List of links to exclude
exclude_links = {
    "LIVE:  TRENDING...": "https://trends.google.com/trends/trendingsearches/realtime?geo=US&hl=en-US&category=all",
    "WORLD NEWSPAPERS PAGE ONES": "https://www.pressreader.com/catalog/newspapers",
    "FRONT PAGES UK": "https://news.sky.com/story/thursdays-national-newspaper-front-pages-12427754",
    "BOXOFFICE": "http://boxofficemojo.com/daily/chart/",
    "TV RATINGS": "https://ustvdb.com/ratings/shows/",
    "ABCNEWS": "http://www.abcnews.com/",
    "ATLANTIC": "http://www.theatlantic.com/",
    "AXIOS": "https://www.axios.com/",
    "BBC": "http://news.bbc.co.uk/default.stm",
    "BILLBOARD": "http://www.billboard.com",
    "BOSTON GLOBE": "http://www.boston.com/globe/",
    "BOSTON HERALD": "http://bostonherald.com/news",
    "BREITBART": "https://www.breitbart.com/",
    "BUSINESS INSIDER": "http://www.businessinsider.com/",
    "CBS NEWS": "http://www.cbsnews.com",
    "CBS NEWS LOCAL": "http://cbslocal.com/2015/08/31/daily-news-tips-from-cbs-local-sites/",
    "C-SPAN": "http://www.c-span.org",
    "CHICAGO SUN-TIMES": "http://www.suntimes.com/",
    "CHICAGO TRIB": "http://www.chicagotribune.com",
    "CHRISTIAN SCIENCE": "http://www.csmonitor.com/",
    "CNBC": "http://www.cnbc.com/",
    "CNN": "http://www.cnn.com",
    "CRAZY DAYS AND NIGHTS": "https://www.crazydaysandnights.net/",
    "DAILY BEAST": "http://thedailybeast.com",
    "DAILY CALLER": "http://dailycaller.com/",
    "DEADLINE HOLLYWOOD": "http://www.deadline.com/hollywood/",
    "ENT WEEKLY": "http://www.ew.com/ew/",
    "FOXNEWS": "http://www.foxnews.com",
    "FREE PRESS": "https://www.thefp.com/",
    "HILL": "http://thehill.com",
    "JUST IN": "http://thehill.com/news",
    "H'WOOD REPORTER": "http://www.hollywoodreporter.com",
    "HUFFINGTON POST": "http://www.huffingtonpost.com",
    "INTERCEPT": "https://theintercept.com/",
    "LA DAILY NEWS": "http://www.dailynewslosangeles.com/",
    "LA TIMES": "http://www.latimes.com",
    "MARKETWATCH": "https://www.marketwatch.com/",
    "MEDIAITE": "https://www.mediaite.com/",
    "MOTHER JONES": "http://www.motherjones.com/",
    "NATION": "http://www.TheNation.com",
    "NATIONAL REVIEW": "http://www.nationalreview.com",
    "NBC NEWS": "http://www.nbcnews.com/",
    "NEW REPUBLIC": "http://www.thenewrepublic.com/",
    "NEW YORK": "http://nymag.com",
    "NY DAILY NEWS": "http://www.nydailynews.com/",
    "NY POST": "http://www.nypost.com/",
    "NY TIMES": "http://www.nytimes.com",
    "WIRE": "http://www.nytimes.com/timeswire/",
    "NEW YORKER": "http://www.newyorker.com",
    "NEWSMAX": "http://www.newsmax.com",
    "NEWZIT": "https://www.newzit.com/",
    "PEOPLE": "http://www.people.com",
    "POLITICO": "http://www.politico.com/",
    "RAW STORY": "https://www.rawstory.com/",
    "REASON": "https://reason.org/",
    "ROLL CALL": "http://www.rollcall.com/",
    "ROLLING STONE": "http://www.rollingstone.com",
    "SALON": "http://www.salon.com/",
    "SAN FRAN CHRON": "http://www.sfgate.com/chronicle/",
    "SEMAFOR": "https://www.semafor.com/",
    "SHOWBIZ 411": "http://www.showbiz411.com",
    "SKY NEWS": "http://news.sky.com/",
    "LIVE": "https://news.sky.com/watch-live",
    "SMOKING GUN": "http://thesmokinggun.com/",
    "TMZ": "http://www.TMZ.com",
    "US NEWS": "http://www.usnews.com/usnews/home.htm",
    "USA TODAY": "http://www.usatoday.com/",
    "VANITY FAIR": "http://www.vanityfair.com",
    "VARIETY": "http://www.variety.com/",
    "WALL STREET JOURNAL": "http://online.wsj.com/home-page",
    "WASH EXAMINER": "http://www.washingtonexaminer.com/",
    "WASH POST": "http://www.washingtonpost.com/",
    "LATEST": "https://www.washingtonpost.com/latest-headlines/",
    "WASH TIMES": "http://www.washingtontimes.com",
    "WRAP": "https://www.thewrap.com/",
    "AFRICAN NEWS": "https://www.africanews.com/",
    "ARAB NEWS": "https://www.arabnews.com/",
    "BILD": "https://www.bild.de/politik/international/bild-international/home-44225950.bild.html",
    "CHINA PEOPLE'S DAILY": "http://en.people.cn/",
    "CLARIN": "https://www.clarin.com/",
    "DIE WELT": "https://www.welt.de/",
    "DIE ZEIT": "https://www.zeit.de/english/index",
    "ECONOMIST": "https://www.economist.com/",
    "EL MUNDO": "https://www.elmundo.es/",
    "EL PAIS": "https://english.elpais.com/",
    "FOLHA DE S. PAULO": "https://www1.folha.uol.com.br/internacional/en/",
    "GBN": "https://www.gbnews.com/",
    "HAARETZ": "https://www.haaretz.com/",
    "HINDUSTAN TIMES": "https://www.hindustantimes.com/",
    "FINANCIAL TIMES": "http://www.ft.com",
    "GAZETA WYBORCZA": "https://wyborcza.pl/0,0.html",
    "HURRIYET": "https://www.hurriyetdailynews.com/",
    "JAPAN TIMES": "https://www.japantimes.co.jp/",
    "JERUSALEM POST": "http://www.jpost.com",
    "LA PRENSA": "https://www.la-prensa.com.mx/",
    "LA  REPUBBLICA": "https://www.repubblica.it/",
    "LE FIGARO": "https://www.lefigaro.fr/",
    "LE MONDE": "https://www.lemonde.fr/en/",
    "LE SOIR": "https://www.lesoir.be/",
    "MOSCOW TIMES": "https://www.themoscowtimes.com/",
    "NEW EUROPEAN": "https://www.theneweuropean.co.uk/",
    "NIKKEI ASIA": "https://asia.nikkei.com/",
    "RIO TIMES": "https://www.riotimesonline.com/",
    "SYDNEY MORNING HERALD": "https://www.smh.com.au/",
    "TIMES OF INDIA": "https://timesofindia.indiatimes.com/us",
    "[UK] DAILY MAIL": "http://www.dailymail.co.uk/home/index.html",
    "FEED": "http://www.dailymail.co.uk/news/headlines/index.html",
    "[UK] DAILY MIRROR": "http://www.mirror.co.uk",
    "[UK] EXPRESS": "http://www.express.co.uk",
    "[UK] GUARDIAN": "https://www.theguardian.com/uk?INTCMP=CE_UK",
    "[UK] INDEPENDENT": "http://www.independent.co.uk/",
    "[UK] METRO": "https://metro.co.uk/",
    "[UK] STANDARD": "https://www.standard.co.uk/",
    "[UK] SUN": "http://www.thesun.co.uk",
    "[UK] TELEGRAPH": "https://www.telegraph.co.uk/",
    "[UK] TIMES": "https://www.thetimes.com/",
    "YOMIURI SHIMBUN": "https://japannews.yomiuri.co.jp/",
    "AGENCE FRANCE-PRESSE": "http://www.france24.com/en/timeline/global/",
    "AP TOP": "https://apnews.com/",
    "AP RADIO": "http://player.streamguys.com/apnews/sgplayer/player.php",
    "BLOOMBERG": "http://www.bloomberg.com/?pid=20601087&sid=a0giIbmAzkss&pos=7",
    "DEUTSCHE PRESSE-AGENTUR": "https://nordot.app/-/units/601684660556563553",
    "DEUTCHE WELLE": "https://www.dw.com/en/top-stories/s-9097",
    "INTERFAX": "http://www.interfax.com/news.asp",
    "ITAR-TASS": "http://www.itar-tass.com/en/",
    "KYODO": "https://english.kyodonews.net/",
    "MCCLATCHY [DC]": "http://www.mcclatchydc.com",
    "NHK": "https://www3.nhk.or.jp/nhkworld/en/news/",
    "PRAVDA": "http://www.pravdareport.com/world/",
    "PRESS TRUST INDIA": "http://www.ptinews.com/",
    "REUTERS": "http://www.reuters.com/",
    "POLITICS": "http://www.reuters.com/news/archive/politicsNews?date=today",
    "WORLD": "http://www.reuters.com/news/archive/worldNews?date=today",
    "XINHUA": "http://www.xinhuanet.com/english/world/index.htm",
    "YONHAP": "http://english.yonhapnews.co.kr/",
    "ARCHIVES": "http://www.drudgereportArchives.com/",
    "RECENT HEADLINES...": "http://www.drudgereportarchives.com/dsp/timeline_html.htm",
    "WEATHER ACTION": "/wx.htm",
    "ZOOM EARTH": "https://zoom.earth/",
    "QUAKE SHEET": "/quake.htm",
    "EMAIL: DRUDGE@DRUDGEREPORT.COM": "mailto:drudge@drudgereport.com",
    "PRIVACY POLICY": "/privacy/",
    "CALIFORNIA NOTICE": "/privacy/california/",
    "OPT-OUT CHOICES": "/privacy/opt-out/"
}